apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.k8sServiceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.name }}

