replicaCount: 1

image:
  repository: devblogs1/mcp-server
  tag: "v2.5"
  pullPolicy: Always

Namespace: default

k8sServiceAccount:
  name: mcp-service-account

serviceAccount:
  name: service-account-8@mig-test-project-456610.iam.gserviceaccount.com 

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: "0.1"
    memory: "128Mi"
  limits:
    cpu: "0.25"
    memory: "256Mi"
